package com.iOfficeProject.trialproject.APIclasses;

import java.util.List;

public class WorkPlace {
	
	private List <WorkPlace> workplaces;
	private String _id;
	private String name;
	private String address;
	private String timezone;
	private String group;
	private String startDate;
	private String endDate;
	private int activeStartHour;
	private int activeEndHour;
	
	
//	private String id;
//	private String name;
//	private String address;
//	private Group group;
//	private String owner;
//	private String formattedAddress;
//	private Location location;
//	private String timezone;
//	private boolean sleep;
//	private String start;
//	private String end;
//	private String activeStartHour;
//	private String activeEndHour;
	
	
	
	
	public WorkPlace() {
	}

	public String get_id() {
		return _id;
	}

	public void set_id(String _id) {
		this._id = _id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTimezone() {
		return timezone;
	}

	public void setTimezone(String timezone) {
		this.timezone = timezone;
	}

	public String getGroup() {
		return group;
	}

	public void setGroup(String group) {
		this.group = group;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public int getActiveStartHour() {
		return activeStartHour;
	}

	public void setActiveStartHour(int activeStartHour) {
		this.activeStartHour = activeStartHour;
	}

	public int getActiveEndHour() {
		return activeEndHour;
	}

	public void setActiveEndHour(int activeEndHour) {
		this.activeEndHour = activeEndHour;
	}

	public List <WorkPlace> getWorkplaces() {
		return workplaces;
	}

	public void setWorkplaces(List <WorkPlace> workplaces) {
		this.workplaces = workplaces;
	}
	
	
}

	
	
//Everything below this point is what was generated by jsonschema2pojo:


//import java.util.HashMap;
//import java.util.List;
//import java.util.Map;
//
////import org.apache.commons.lang.builder.EqualsBuilder;
////import org.apache.commons.lang.builder.HashCodeBuilder;
////import org.apache.commons.lang.builder.ToStringBuilder;
//
//import com.fasterxml.jackson.annotation.JsonAnyGetter;
//import com.fasterxml.jackson.annotation.JsonAnySetter;
//import com.fasterxml.jackson.annotation.JsonIgnore;
//import com.fasterxml.jackson.annotation.JsonInclude;
//import com.fasterxml.jackson.annotation.JsonProperty;
//import com.fasterxml.jackson.annotation.JsonPropertyOrder;
//
//	@JsonInclude(JsonInclude.Include.NON_NULL)
//	@JsonPropertyOrder({
//	"type",
//	"coordinates"
//	})
//	public class WorkPlace {
//
//	@JsonProperty("type")
//	private String type;
//	@JsonProperty("coordinates")
//	private List<Double> coordinates = null;
//	@JsonIgnore
//	private Map<String, Object> additionalProperties = new HashMap<String, Object>();
//
//	/**
//	* No args constructor for use in serialization
//	* 
//	*/
//	public WorkPlace() {
//	}
//
//	/**
//	* 
//	* @param type
//	* @param coordinates
//	*/
//	public WorkPlace(String type, List<Double> coordinates) {
//	super();
//	this.type = type;
//	this.coordinates = coordinates;
//	}
//
//	@JsonProperty("type")
//	public String getType() {
//	return type;
//	}
//
//	@JsonProperty("type")
//	public void setType(String type) {
//	this.type = type;
//	}
//
//	@JsonProperty("coordinates")
//	public List<Double> getCoordinates() {
//	return coordinates;
//	}
//
//	@JsonProperty("coordinates")
//	public void setCoordinates(List<Double> coordinates) {
//	this.coordinates = coordinates;
//	}
//
//	@JsonAnyGetter
//	public Map<String, Object> getAdditionalProperties() {
//	return this.additionalProperties;
//	}
//
//	@JsonAnySetter
//	public void setAdditionalProperty(String name, Object value) {
//	this.additionalProperties.put(name, value);
//	}
//
//	@Override
//	public String toString() {
//		return "WorkPlace [type=" + type + ", coordinates=" + coordinates + ", additionalProperties="
//				+ additionalProperties + "]";
//	}

//	@Override
//	public String toString() {
//	return new ToStringBuilder(this).append("type", type).append("coordinates", coordinates).append("additionalProperties", additionalProperties).toString();
//	}
//
//	@Override
//	public int hashCode() {
//	return new HashCodeBuilder().append(additionalProperties).append(type).append(coordinates).toHashCode();
//	}
//
//	@Override
//	public boolean equals(Object other) {
//	if (other == this) {
//	return true;
//	}
//	if ((other instanceof Location) == false) {
//	return false;
//	}
//	Location rhs = ((Location) other);
//	return new EqualsBuilder().append(additionalProperties, rhs.additionalProperties).append(type, rhs.type).append(coordinates, rhs.coordinates).isEquals();
//	}
	
	





